### ISSUE TITLE
ADDomain: attempt counting issue

### ISSUE THREAD

**Issue by dcrreynolds** [PowerShell/ActiveDirectoryDsc#181]
xADDomin is struggling counting giving me the error below.

Attempt 6 of 5 to call Get-ADDomain Failed.

![6of5](https://user-images.githubusercontent.com/12203247/35460387-7803b746-02a9-11e8-8f4d-21264f6a066c.PNG)

**Comment by johlju** [comment]
If think it's a logical error here. The `$domainShouldExist` I can't see it being assigned again in the `do-while`-loop, and it should probably be a `-or` instead of `-and` in the evaluation. That's why you are seeing 'Attempt 6 of 5...'.

https://github.com/PowerShell/xActiveDirectory/blob/e858c98fceb3e1b2039ea9a0884e66cac0bdc8cb/DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1#L170

**Comment by GoateePFE** [comment]
+1 on WS2016

**Comment by jrdnr** [comment]
@johlju Just ran into this trying to build a lab domain,  I think the `-and` on [line 170](https://github.com/PowerShell/xActiveDirectory/blob/e858c98fceb3e1b2039ea9a0884e66cac0bdc8cb/DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1#L170) is intentional, I'm a little less clear on why it is not working. 

immediately [before](https://github.com/PowerShell/xActiveDirectory/blob/e858c98fceb3e1b2039ea9a0884e66cac0bdc8cb/DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1#L106) the `do{` loop `$domainShouldExist` should be getting set to `$true` or `$false`  Which if the domain does not exist (`$false`) should allow loop to run once and exit, which would be desired behavior on a new domain.  

Oddly when I attempted to apply the DSC to a clean WS2016, with `-Verbose` it prints the Verbose output from the [line 166](https://github.com/PowerShell/xActiveDirectory/blob/e858c98fceb3e1b2039ea9a0884e66cac0bdc8cb/DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1#L166) which should only run `if ($domainShouldExist)`

As a quick hack for troubleshooting I added `Write-Verbose "`$domainShouldExist = $domainShouldExist"` inside the do loop and everything just worked as expected.  I'm not quite sure what is going on.

**Comment by johlju** [comment]
Hmm.. Since this happens inconsequentially, maybe we should add in `Write-Verbose` outputting nice "debug" messages with the variables more frequently so that it's possible to trace what happened. 
For example
```
$domainShouldExist = (Test-Path (Get-TrackingFilename -DomainName $DomainName))
if ($domainShouldExist)
{
    Write-Verbose -Message 'Found the tracking file, the domain should exist.'
}
else
{
    Write-Verbose -Message 'Did not find the tracking file, the domain does not exist.'
}
```

Other suggestions?

**Comment by devopsjesus** [comment]
Hi all,

I kept running into this during a lab setup, so I tracked my issue down to this scenario:

If the `Install-ADDSDomain` cmdlet fails during the **initial** consistency check, the tracking file is still written to the temp folder, since it seems there is currently no error handling for that cmdlet in the Set-TargetResource function:

```
if ($PSBoundParameters.ContainsKey('ParentDomainName'))
{
    Write-Verbose -Message ($localizedData.CreatingChildDomain -f $DomainName, $ParentDomainName);
    $installADDSParams['Credential'] = $DomainAdministratorCredential
    $installADDSParams['NewDomainName'] = $DomainName
    $installADDSParams['ParentDomainName'] = $ParentDomainName
    $installADDSParams['DomainType'] = 'ChildDomain';
    if ($PSBoundParameters.ContainsKey('DomainNetBIOSName'))
    {
        $installADDSParams['NewDomainNetbiosName'] = $DomainNetBIOSName;
    }
    Install-ADDSDomain @installADDSParams;
    Write-Verbose -Message ($localizedData.CreatedChildDomain);
}
else
{
    Write-Verbose -Message ($localizedData.CreatingForest -f $DomainName);
    $installADDSParams['DomainName'] = $DomainName;
    if ($PSBoundParameters.ContainsKey('DomainNetbiosName'))
    {
        $installADDSParams['DomainNetbiosName'] = $DomainNetBIOSName;
    }
    if ($PSBoundParameters.ContainsKey('ForestMode'))
    {
        $installADDSParams['ForestMode'] = $ForestMode
    }
    Install-ADDSForest @installADDSParams;
    Write-Verbose -Message ($localizedData.CreatedForest -f $DomainName);
}

'Finished' | Out-File -FilePath (Get-TrackingFilename -DomainName $DomainName) -Force
```
Then, every time the resource runs, the Get-TargetResource function will see the tracking file, and `$domainShouldExist` returns $true.  The script continues but will error on the Get-ADDomain cmdlet, and error handling will default to retrying the loop, and the loop is errantly restarted.  (The loop counting issue is likely a simple math error in the code.)

Propose adding error handling of some kind to the `Install-ADDSDomain` cmdlet (probably the forest cmdlet too) so that the file is not written in case of error:
```
$failed = $false
if ($PSBoundParameters.ContainsKey('ParentDomainName'))
{
    Write-Verbose -Message ($localizedData.CreatingChildDomain -f $DomainName, $ParentDomainName);
    $installADDSParams['Credential'] = $DomainAdministratorCredential
    $installADDSParams['NewDomainName'] = $DomainName
    $installADDSParams['ParentDomainName'] = $ParentDomainName
    $installADDSParams['DomainType'] = 'ChildDomain';
    if ($PSBoundParameters.ContainsKey('DomainNetBIOSName'))
    {
        $installADDSParams['NewDomainNetbiosName'] = $DomainNetBIOSName;
    }
    Try
    {
        Install-ADDSDomain @installADDSParams;
        Write-Verbose -Message ($localizedData.CreatedChildDomain);
    }
    catch
    {
        $failed = $true
        Write-Verbose -Message ($localizedData.FailedDomainCreation);
    }
    ...
}

if (! $failed)
{
    'Finished' | Out-File -FilePath (Get-TrackingFilename -DomainName $DomainName) -Force
}
```

**Comment by johlju** [comment]
> the reason `Install-ADDSDomain` cmdlet failed for me was because I was mistakenly passing a Single-label DNS name for the DomainName property value, so there is also a need for input validation as well perhaps?

When configuring a child domain the domain name must be set to a single-label DNS name. So a validation would need to take that in account when `ParentDomainName` is also specified.
